
/**
 * @file bytewidth_lookup_table.gen.h
 * @author Ege Özkan (elsaambertide@gmail.com)
 * @brief Private header file autogenerated with generate_byte_lookup.py
 * in the same source directory.
 * @version 0.1
 * @date 2025-04-27
 *
 * @copyright Copyright (c) 2025
 *
 */

#ifndef BEEMU_TOKENIZER_BYTEWIDTH_LOOKUP_TABLE_GEN_H
#define BEEMU_TOKENIZER_BYTEWIDTH_LOOKUP_TABLE_GEN_H
#include <stdint.h>
#ifdef __cplusplus
extern "C"
{
#endif

	const uint8_t PRE_0X40_BYTE_LENGTH_LOOKUP[] = {1, 3, 1, 1, 1, 1, 2, 1, 3, 1, 1, 1, 1, 1, 2, 1, 2, 3, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 3, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 3, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1};
	const uint8_t POST_0XBF_BYTE_LENGTH_LOOKUP[] = {1, 1, 3, 3, 3, 1, 2, 1, 1, 1, 3, 1, 3, 3, 2, 1, 1, 1, 3, 1, 3, 1, 2, 1, 1, 1, 3, 1, 3, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 3, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 3, 1, 1, 1, 2, 1};

#ifdef __cplusplus
}
#endif

#endif // BEEMU_TOKENIZER_BYTEWIDTH_LOOKUP_TABLE_GEN_H
