name: Build and Test Template

# This structure is as per https://github.com/orgs/community/discussions/42335#discussioncomment-7997348
# To support multiple OS's accross multiple jobs.

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{inputs.os}}

    outputs:
      # This one is required to trigger downstream
      # jobs with the same operating system.
      os: ${{inputs.os}}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'


      - name: Switch to gcc-14 on linux
        # as per https://stackoverflow.com/a/67791068
        if: inputs.os == 'ubuntu-24.04'
        run: |
          sudo add-apt-repository -y universe && sudo apt -y update && sudo apt install -y gcc-14 g++-14          
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100 --slave /usr/bin/g++ g++ /usr/bin/g++-14 --slave /usr/bin/gcov gcov /usr/bin/gcov-14
          sudo update-alternatives --set gcc /usr/bin/gcc-14

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Tar build artifacts
        working-directory: ${{github.workspace}}
        # Tar is required to maintain permissions
        run: tar -cvf beemu-build-${{inputs.os}}.tar build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: beemu-build-${{inputs.os}}
          path: beemu-build-${{inputs.os}}.tar

  test:
    needs: build
    runs-on: ${{inputs.os}}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Download build artifacts for ${{inputs.os}}
        uses: actions/download-artifact@v5
        with:
          name: beemu-build-${{inputs.os}}
      - name: Unarchive build artifacts for ${{inputs.os}}
        run: tar -xvf beemu-build-${{inputs.os}}.tar
      - name: Test
        working-directory: ${{github.workspace}}/build
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C ${{env.BUILD_TYPE}} -j 0

