name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
    build:
      strategy:
        matrix:
          os: [ 'ubuntu-24.04' ]

      runs-on: ${{ matrix.os}}

      outputs:
        # This one is required to trigger downstream
        # jobs with the same operating system.
        os: ${{matrix.os}}
      steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'


      - name: Switch to gcc-14 on linux
        # as per https://stackoverflow.com/a/67791068
        if: matrix.os == 'ubuntu-24.04'
        run: |
          sudo add-apt-repository -y universe && sudo apt -y update && sudo apt install -y gcc-14 g++-14          
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100 --slave /usr/bin/g++ g++ /usr/bin/g++-14 --slave /usr/bin/gcov gcov /usr/bin/gcov-14
          sudo update-alternatives --set gcc /usr/bin/gcc-14

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: beemu-build-${{matrix.os}}
          path: ${{github.workspace}}/build

    test:
      needs: build
      runs-on: ${{needs.build.outputs.os}}
      steps:
      - name: Download build artifacts for ${{needs.build.outputs.os}}
        uses: actions/download-artifact@v5
        with:
          name: beemu-build-${{needs.build.outputs.os}}
          path: ${{github.workspace}}/build
      - name: Test
        working-directory: ${{github.workspace}}/build
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C ${{env.BUILD_TYPE}} -j 0

